### PR TITLE
Explicitly define "types" field

### PR DESCRIPTION
**Pull request by chanlito**

### CODE REVIEW

**Comment by AndrewBogdanovTSS** [comment]
When will this be approved and integrated?

**Comment by chanlito** [comment]
@AndrewBogdanovTSS I dunno 😆I currently using my own module.

**Comment by AndrewBogdanovTSS** [comment]
Guys, it's a simple 1 liner, please, push it to prod

**Comment by leozero** [comment]
Yeah it would be great

**Comment by dojineko** [comment]
please merge this~ 😭

**Pull request merged**
